name: user_repository
description: Dart package which manages the user.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.17.0
  firebase_core: ^2.25.1
  firebase_storage: ^11.6.2
  cloud_firestore: ^4.15.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
