name: explore_ez
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  equatable: ^2.0.5
  firebase_auth: ^4.17.0
  firebase_core: ^2.25.1


  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_native_splash: ^2.3.10
  user_repository:
    path: packages/user_repository
  trip_repository:
    path: packages/trip_repository
  area_repository:
    path: packages/area_repository
  plan_repository:
    path: packages/plan_repository
  bloc: ^8.1.3
  intl: ^0.19.0
  get: ^4.6.6
  http: ^1.2.0
  google_fonts: ^6.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/background/

flutter_native_splash:
  color: "#f9f9f9"
  image: "assets/logo_white.png"
  color_dark: "#000000"
  image_dark: "assets/logo_dark.png"

  
  android_12:
    color: "#f9f9f9"
    image: "assets/logo_white.png"
    color_dark: "#000000"
    image_dark: "assets/logo_dark.png"

