name: plan_repository
description: Dart package which manages the tour plan.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  area_repository:
    path: ../area_repository
  http: ^1.2.0
  location: ^5.0.3
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true